# Generated by Django 3.0 on 2019-12-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved', models.IntegerField(default=3)),
                ('defined', models.IntegerField(default=3)),
                ('appropriate', models.IntegerField(default=3)),
                ('simplicity', models.IntegerField(default=3)),
                ('clarity', models.IntegerField(default=3)),
                ('volume', models.IntegerField(default=3)),
            ],
        ),
    ]
