# Generated by Django 3.0 on 2019-12-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackform',
            name='achieved',
            field=models.IntegerField(default=3, verbose_name='Were Course Objectives Achieved?'),
        ),
    ]
