# Generated by Django 3.0 on 2019-12-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_feedback', '0002_auto_20191210_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackform',
            name='disliked',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feedbackform',
            name='liked',
            field=models.TextField(blank=True),
        ),
    ]
