# Generated by Django 3.0 on 2019-12-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_feedback', '0004_auto_20191210_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackform',
            name='e_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Participant ID'),
        ),
        migrations.AddField(
            model_name='feedbackform',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email ID'),
        ),
        migrations.AddField(
            model_name='feedbackform',
            name='name',
            field=models.CharField(blank=True, default='anonymous', max_length=100, verbose_name='Name of the Participant'),
        ),
    ]
